pipeline:

  start_year: 2023

  taxi_type: yellow

storage:

  bronze_path: data/bronze

  silver_path: data/silver

  gold_path: data/gold

download:

  base_url: https://d37ci6vzurychx.cloudfront.net

quality:

  max_passengers: 6

  max_fare_amount: 1000