storage:

  bronze_path: s3://nyc-taxi-analytics/bronze-dibya/trip_data/

  silver_path: s3://nyc-taxi-analytics-dibya/silver/trips/

  gold_path: s3://nyc-taxi-analytics-dibya/gold/

lookup:

  taxi_zone_path: s3://nyc-taxi-analytics-dibya/bronze/lookup/taxi_zone_lookup.csv

pipeline:

  processing_year: 2023

spark:

  shuffle_partitions: 8