CREATE OR REPLACE WAREHOUSE NYC_TAXI_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

SHOW WAREHOUSES;

CREATE OR REPLACE DATABASE NYC_TAXI_DB;

USE DATABASE NYC_TAXI_DB;

CREATE OR REPLACE SCHEMA ANALYTICS;

USE WAREHOUSE NYC_TAXI_WH;

USE DATABASE NYC_TAXI_DB;

USE SCHEMA ANALYTICS;



